# Name of entire workflow
name: Shell Commands

#Commands that triggers the workflows with the "on" prefix.
#on: [push]
on:
  repository_dispatch:
    types:
      #the same name should be in the api call(or anything else) that 
      #triggers it.
      ["build"]
  # schedule:
  #   - cron: "* * * * *"
  # push:
  pull_request:
    types:
      [closed, assigned, opened, reopened]

#Name of each job is the key uder the prefix "jobs"
#Each job can have multiple options and inside an object.
#Steps has multiple objects which indicates each step.
#Steps can be an action or an cmd command
jobs:
    run-shell-command:
       runs-on: ubuntu-latest
       steps:
        - name: echo a string
          run: echo "Hello, World!"
          continue-on-error: false
        - name: multiline script commands
          run: | #Use again the pipe | to run mupliple line commands
            node -v
            npm -v
        - name: python Commands
          run: |
            import platform
            print
            (platform.processor())
          shell: python
    #Default windows shell is powershell
    run-windows-commands:
      runs-on: windows-latest
      needs: ["run-shell-command"]
      steps:
        - name: Directory Powershell
          run: Get-Location
        - name: Directory Bash
          run: pwd
          shell: bash
